### PR TITLE
Fix code syntax highlighting

### PR DESCRIPTION
**Pull request by jkresner**

### CODE REVIEW

**Comment by larskotthoff** [comment]
Thanks, merged!

**Comment by jkresner** [comment]
Can we update this gravatar? I feel like we've done this before :)

https://0.gravatar.com/avatar/735c2df2df48481bdd5dfd37155326a4
ᐧ

On Fri, Mar 13, 2015 at 10:08 AM, Lars Kotthoff notifications@github.com
wrote:

> Thanks, merged!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airpair/d3-force-layout-internals/pull/1#issuecomment-79142405
> .

## 

Jonathon Kresner
about.me http://about.me/jonathonkresner | hackerpreneurialism
http://hackerpreneurialism.com | @hackerpreneur
http://twitter.com/hackerpreneur

**Comment by larskotthoff** [comment]
Which email address did you use for this? Just set up my gmail, but it doesn't
seem to update.

Cheers,

Lars

**Comment by jkresner** [comment]
Looks fixed now!
ᐧ

On Fri, Mar 13, 2015 at 10:17 AM, Lars Kotthoff notifications@github.com
wrote:

> Which email address did you use for this? Just set up my gmail, but it
> doesn't
> seem to update.
> 
> Cheers,
> 
> Lars
> 
> On Fri, 13 Mar 2015 10:10:03 -0700
> Jonathon Kresner notifications@github.com wrote:
> 
> > Can we update this gravatar? I feel like we've done this before :)
> > 
> > https://0.gravatar.com/avatar/735c2df2df48481bdd5dfd37155326a4
> > ᐧ
> > 
> > On Fri, Mar 13, 2015 at 10:08 AM, Lars Kotthoff <
> > notifications@github.com>
> > wrote:
> > 
> > > Thanks, merged!
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > > https://github.com/airpair/d3-force-layout-internals/pull/1#issuecomment-79142405
> > > 
> > > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/airpair/d3-force-layout-internals/pull/1#issuecomment-79151332
> .

## 

Jonathon Kresner
about.me http://about.me/jonathonkresner | hackerpreneurialism
http://hackerpreneurialism.com | @hackerpreneur
http://twitter.com/hackerpreneur

**Pull request merged**
